- name: Pull Docker image from registry
  hosts: docker-host
  become: true
  vars:
    registry: sldp09i3.gra7.container-registry.ovh.net/poc-ocsge
  tasks:
    - name: Log in to registry
      shell: cat /home/harbor/pw| docker login {{ registry }} --username poc-ocsge --password-stdin

    - name: Pull Docker image ocsge
      shell: docker pull {{ registry }}/ocsge:poc343v3

    - name: Pull Docker image odeon
      shell: docker pull {{ registry }}/odeon:2.1.7
