- name: Afficher le contenu d'un fichier sur la cible dans le master
  hosts: gpu_servers
  become: true

  tasks:

    - name: Trouver le chemin du fichier group*.txt
      find:
        paths: /var/tmp
        patterns: dalles_detection_temps_grou*.log
        recurse: no
        file_type: file
      register: found_file

    - name: Copier le fichier log de la cible vers le master
      fetch:
        src: "{{ found_file.files[0].path }}"
        dest: /home/ubuntu/workdir/results/{{ inventory_hostname }}.log
        flat: yes
      register: result

    - name: Copier le fichier de monitoring gpu de la cible vers le master
      fetch:
        src: /var/tmp/monitoring_gpu.txt
        dest: /home/ubuntu/workdir/results//var/tmp/monitoring_gpu_{{ inventory_hostname }}.txt
        flat: yes
      register: result
