- name: Afficher le nom et l'OS de chaque machine
  hosts: gpu_servers
  gather_facts: true

  tasks:
    - name: Afficher le nom et l'OS de la machine
      debug:
        msg: "Nom de la machine : {{ inventory_hostname }}, OS : {{ ansible_distribution }} {{ ansible_distribution_version }}"
